image: node:lts

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
    - mkdir public
    - cp -r dist/* public/

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
